version: '3'
services:
  scrapy_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

